### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by willprice** [jmerle/zeal-user-contrib#2]
Hi jmerle,
Thank you for this fantastic piece of work, it's been super handy. 
I noticed today that https://zealusercontributions.herokuapp.com/ is down, any chance it can be resurrected?

Many thanks for your time and efforts

**Comment by jmerle** [comment]
Given today's date this seems to be related to https://github.com/xantiagoma/zealusercontributions/issues/1 and https://github.com/xantiagoma/zealusercontributions/issues/2. I'll switch the domain from [zealusercontributions.herokuapp.com](https://zealusercontributions.herokuapp.com/) to the [zealusercontributions.now.sh](https://zealusercontributions.now.sh/) mirror which doesn't seem to be affected by monthly quotas.

Note that this change will only be available for newly added docsets, due to the way the CLI is set up I cannot easily add a new command (like `zeal-user-contrib migrate`) that migrates existing docsets from the [zealusercontributions.herokuapp.com](https://zealusercontributions.herokuapp.com/) domain to the [zealusercontributions.now.sh](https://zealusercontributions.now.sh/) mirror.

**Comment by jmerle** [comment]
This is going to take a little longer, at least until the [zealusercontributions.herokuapp.com](https://zealusercontributions.herokuapp.com/) domain is back up. If I change the feed urls to the mirror, Zeal starts to function in unexpected ways where after adding a docset via the CLI, it always thinks it is outdated and creates a new docset for the docset you just added but trims the name (so if you add the PlantUML docset, restart Zeal and open the docsets window, it creates a "Plan" docset with the content of the PlantUML docset). I have no clue what is causing this issue, so I'm going to wait for  [zealusercontributions.herokuapp.com](https://zealusercontributions.herokuapp.com/) to come back online to see what the differences between that and the mirror are.

**Comment by jmerle** [comment]
I've found the issue and send a PR to the zealusercontributions project because their API currently doesn't allow feed urls to have a `.xml` prefix, which Zeal <= 0.6.1 requires to be the case. When https://github.com/xantiagoma/zealusercontributions/pull/5 gets merged I'll deploy a zeal-user-contrib update which changes from the herokuapp.com domain to the now.sh domain.

**Comment by willprice** [comment]
Wonderful, thank you jmerle for your speedy work, much appreciated!

**Comment by jmerle** [comment]
Released in [v1.1.0](https://github.com/jmerle/zeal-user-contrib/releases/tag/v1.1.0).
